# Generated by Django 4.2.5 on 2023-10-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bicycle_image', models.ImageField(blank=True, null=True, upload_to='store/products/bicycles/%Y/%m/%d/')),
                ('bicycle_price', models.IntegerField()),
                ('bicycle_name', models.CharField(max_length=300)),
                ('bicycle_frame_size', models.IntegerField()),
                ('bicycle_number_of_speeds', models.IntegerField()),
                ('bicycle_type', models.CharField(max_length=100)),
                ('bicycle_class', models.CharField(max_length=100)),
                ('bicycle_manufacturer_country', models.CharField(max_length=100)),
                ('bicycle_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
