# Generated by Django 4.2.5 on 2023-10-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productbicycle_bicycle_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbicycle',
            name='bicycle_type_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/products/bicycles/%Y/%m/%d/'),
        ),
    ]
