# Generated by Django 4.2.5 on 2023-10-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productaccessory_productclothes_productsparepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/products/%Y/%m/%d/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='store/products/icons/%Y/%m/%d/')),
                ('category', models.CharField(blank=True, max_length=300)),
                ('type', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('brand', models.CharField(blank=True, max_length=300)),
                ('price', models.FloatField()),
                ('manufacturer_country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sizes', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=100, null=True)),
                ('frame_size', models.IntegerField(null=True)),
                ('wheel_size', models.IntegerField(null=True)),
                ('number_of_speeds', models.IntegerField(null=True)),
            ],
        ),
    ]
