# Generated by Django 4.2.5 on 2023-10-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
