# Generated by Django 4.2.5 on 2023-10-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaccessory',
            name='accessory_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productclothes',
            name='clothes_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsparepart',
            name='spare_part_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
