# Generated by Django 4.2.5 on 2023-10-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productaccessory_accessory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbicycle',
            name='bicycle_image1',
            field=models.ImageField(blank=True, null=True, upload_to='store/products/bicycles/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='productbicycle',
            name='bicycle_image2',
            field=models.ImageField(blank=True, null=True, upload_to='store/products/bicycles/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='productbicycle',
            name='bicycle_image3',
            field=models.ImageField(blank=True, null=True, upload_to='store/products/bicycles/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='productbicycle',
            name='bicycle_image4',
            field=models.ImageField(blank=True, null=True, upload_to='store/products/bicycles/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='productbicycle',
            name='bicycle_image5',
            field=models.ImageField(blank=True, null=True, upload_to='store/products/bicycles/%Y/%m/%d/'),
        ),
    ]
