# Generated by Django 4.2.5 on 2023-10-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productbicycle_bicycle_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbicycle',
            old_name='bicycle_price',
            new_name='bicycle_price_new',
        ),
        migrations.RemoveField(
            model_name='productbicycle',
            name='bicycle_image5',
        ),
        migrations.AddField(
            model_name='productbicycle',
            name='bicycle_price_old',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productbicycle',
            name='bicycle_frame_size',
            field=models.PositiveSmallIntegerField(choices=[(1, 'M'), (2, 'L'), (3, 'XL'), (0, 'S')], default=0),
        ),
    ]
