# Generated by Django 4.2.5 on 2023-10-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_bicycle_price_productbicycle_bicycle_price_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_size', models.PositiveSmallIntegerField(choices=[(0, 'S'), (2, 'L'), (3, 'XL'), (1, 'M')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='productbicycle',
            name='bicycle_frame_size',
        ),
        migrations.AddField(
            model_name='productbicycle',
            name='bicycle_frame_sizes',
            field=models.ManyToManyField(blank=True, to='store.framesize'),
        ),
    ]
