# Generated by Django 4.2.5 on 2023-10-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_framesize_remove_productbicycle_bicycle_frame_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framesize',
            name='frame_size',
            field=models.CharField(choices=[(3, 'XL'), (0, 'S'), (2, 'L'), (1, 'M')], default=0, max_length=1),
        ),
    ]
