# Generated by Django 4.2.5 on 2023-10-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_framesize_frame_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framesize',
            name='frame_size',
            field=models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('S', 'S'), ('M', 'M')], default=0, max_length=10),
        ),
    ]
