# Generated by Django 4.2.5 on 2023-10-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_framesize_frame_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_size', models.IntegerField(choices=[(0, 24), (2, 28), (1, 26)], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='productbicycle',
            name='bicycle_wheel_size',
        ),
        migrations.AlterField(
            model_name='framesize',
            name='frame_size',
            field=models.CharField(choices=[('XL', 'XL'), ('S', 'S'), ('M', 'M'), ('L', 'L')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='productbicycle',
            name='bicycle_wheel_sizes',
            field=models.ManyToManyField(blank=True, to='store.wheelsize'),
        ),
    ]
