# Generated by Django 4.2.5 on 2023-10-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_wheelsize_remove_productbicycle_bicycle_wheel_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framesize',
            name='frame_size',
            field=models.CharField(choices=[('M', 'M'), ('S', 'S'), ('XL', 'XL'), ('L', 'L')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='wheelsize',
            name='wheel_size',
            field=models.SmallIntegerField(choices=[(0, 24), (2, 28), (1, 26)], default=0),
        ),
    ]
