# Generated by Django 4.2.5 on 2023-10-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_framesize_frame_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framesize',
            name='frame_size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('S', 'S'), ('XL', 'XL')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='wheelsize',
            name='wheel_size',
            field=models.SmallIntegerField(choices=[(2, '28'), (1, '26'), (0, '24')], default=0),
        ),
    ]
