# Generated by Django 4.2.5 on 2023-10-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_framesize_frame_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framesize',
            name='frame_size',
            field=models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('S', 'S'), ('M', 'M')], max_length=10),
        ),
    ]
