# Generated by Django 4.2.5 on 2023-10-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_framesize_frame_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framesize',
            name='frame_size',
            field=models.CharField(choices=[('XL', 'XL'), ('S', 'S'), ('L', 'L'), ('M', 'M')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wheelsize',
            name='wheel_size',
            field=models.CharField(choices=[('28', '28'), ('24', '24'), ('26', '26')], max_length=10),
        ),
    ]
