# Generated by Django 4.2.5 on 2023-11-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_framesize_frame_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('comments', models.TextField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='framesize',
            name='frame_size',
            field=models.CharField(choices=[('XL', 'XL'), ('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wheelsize',
            name='wheel_size',
            field=models.CharField(choices=[('28', '28'), ('24', '24'), ('26', '26')], max_length=10),
        ),
    ]
